using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using Newtonsoft.Json;

namespace Malyzer.Servicios;

public class GestorIdioma : INotifyPropertyChanged
{
    public static GestorIdioma Instancia { get; } = new();

    public event PropertyChangedEventHandler? PropertyChanged;

    private string idiomaActual = "es";
    private Dictionary<string, Dictionary<string, string>> traducciones = new();

    private GestorIdioma()
    {
        CargarTraducciones();
    }

    public string IdiomaActual
    {
        get => idiomaActual;
        set
        {
            if (idiomaActual == value) return;
            if (!traducciones.ContainsKey(value)) return;
            idiomaActual = value;
            try
            {
                var ci = new CultureInfo(value == "en" ? "en-US" : "es-ES");
                CultureInfo.DefaultThreadCurrentCulture = ci;
                CultureInfo.DefaultThreadCurrentUICulture = ci;
            }
            catch { }
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(IdiomaActual)));
        }
    }

    public string this[string clave]
    {
        get
        {
            if (traducciones.TryGetValue(idiomaActual, out var dic) && dic.TryGetValue(clave, out var v)) return v;
            if (traducciones.TryGetValue("es", out var fb) && fb.TryGetValue(clave, out var f)) return f;
            return clave;
        }
    }

    public string T(string clave) => this[clave];

    public IEnumerable<(string codigo, string nombre)> IdiomasDisponibles()
    {
        yield return ("es", "Español");
        yield return ("en", "English");
    }

    private void CargarTraducciones()
    {
        traducciones["es"] = DiccionarioEs();
        traducciones["en"] = DiccionarioEn();
    }

    private static Dictionary<string, string> DiccionarioEs() => new()
    {
        ["nav.inicio"] = "Panel principal",
        ["nav.estatico"] = "Análisis estático",
        ["nav.dinamico"] = "Sandbox dinámico",
        ["nav.pro"] = "Herramientas pro",
        ["nav.intel"] = "Threat Intel",
        ["nav.ml"] = "Clasificación ML",
        ["nav.visual"] = "Visualización",
        ["nav.muestras"] = "Muestras",
        ["nav.plugins"] = "Plugins",
        ["nav.evasion"] = "Anti-evasión",
        ["nav.urlscan"] = "URL Scan",
        ["nav.advanced"] = "Inteligencia avanzada",
        ["nav.sistema"] = "Sistema",
        ["nav.netsniff"] = "Netsniff",
        ["nav.config"] = "Configuración",
        ["nav.grupo.analisis"] = "ANÁLISIS",
        ["nav.grupo.inteligencia"] = "INTELIGENCIA",
        ["nav.grupo.gestion"] = "GESTIÓN",
        ["nav.grupo.monitoreo"] = "MONITOREO",

        ["estado.listo"] = "Listo",
        ["estado.trabajando"] = "Trabajando...",
        ["estado.error"] = "Error",
        ["estado.muestras"] = "muestras",

        ["btn.guardar"] = "Guardar cambios",
        ["btn.cancelar"] = "Cancelar",
        ["btn.aplicar"] = "Aplicar",
        ["btn.refrescar"] = "Refrescar",
        ["btn.refrescar_todo"] = "Refrescar todo",
        ["btn.examinar"] = "Examinar",
        ["btn.eliminar"] = "Eliminar",
        ["btn.exportar"] = "Exportar",
        ["btn.importar"] = "Importar",
        ["btn.iniciar"] = "Iniciar",
        ["btn.analizar"] = "Analizar",
        ["btn.consultar"] = "Consultar",
        ["btn.limpiar"] = "Limpiar",
        ["btn.recargar"] = "Recargar",
        ["btn.restablecer"] = "Restablecer",
        ["btn.regenerar"] = "Regenerar",

        ["pag.config.titulo"] = "Configuración",
        ["pag.config.subtitulo"] = "Claves de API, rutas a herramientas externas, idioma y opciones de ejecución",
        ["pag.config.idioma"] = "Idioma de la interfaz",
        ["pag.config.idioma_descripcion"] = "Los cambios se aplican al instante en la mayoría de pantallas",
        ["pag.config.api"] = "Claves de API",
        ["pag.config.rutas"] = "Rutas a herramientas externas",
        ["pag.config.sandbox"] = "Sandbox y análisis dinámico",
        ["pag.config.sandbox_aislada"] = "Usar sandbox aislada (recomendado)",
        ["pag.config.enviar_vt"] = "Permitir envío de muestras a VirusTotal",
        ["pag.config.timeout"] = "Timeout dinámico (s)",
        ["pag.config.almacenamiento"] = "Almacenamiento",
        ["pag.config.dir_datos"] = "Directorio de datos",
        ["pag.config.bd"] = "Base de datos",
        ["pag.config.abrir_dir_datos"] = "Abrir directorio de datos",
        ["pag.config.abrir_dir_reportes"] = "Abrir directorio de reportes",
        ["pag.config.guardado"] = "Configuración guardada",
        ["pag.config.confirmar_reset"] = "¿Restablecer todos los valores por defecto?",
        ["pag.config.reglas_yara"] = "Reglas YARA",

        ["pag.inicio.titulo"] = "Inicio",
        ["pag.inicio.subtitulo"] = "Resumen general del laboratorio de análisis",
        ["pag.inicio.muestras_totales"] = "Muestras totales",
        ["pag.inicio.riesgo_alto"] = "Riesgo alto",
        ["pag.inicio.familias"] = "Familias detectadas",
        ["pag.inicio.pendientes"] = "Pendientes de análisis",
        ["pag.inicio.distribucion"] = "Distribución por familia",
        ["pag.inicio.recientes"] = "Últimas muestras",
        ["pag.inicio.acciones"] = "Acciones rápidas",
        ["pag.inicio.entorno"] = "Estado del entorno",
        ["pag.inicio.importar_muestras"] = "Importar muestras",
        ["pag.inicio.lab_operativo"] = "Laboratorio operativo · Listo para analizar",

        ["pag.estatico.titulo"] = "Análisis estático",
        ["pag.estatico.cargar"] = "Cargar archivo",
        ["pag.estatico.veredicto"] = "Veredicto",
        ["pag.estatico.tab_general"] = "General",
        ["pag.estatico.tab_pe"] = "Cabecera PE",
        ["pag.estatico.tab_secciones"] = "Secciones",
        ["pag.estatico.tab_imports"] = "Importaciones",
        ["pag.estatico.tab_strings"] = "Strings",
        ["pag.estatico.tab_iocs"] = "IOCs",
        ["pag.estatico.tab_yara"] = "YARA",

        ["pag.dinamico.titulo"] = "Sandbox dinámico",
        ["pag.dinamico.advertencia"] = "Ejecutá únicamente en una máquina virtual aislada con snapshot",
        ["pag.dinamico.timeout"] = "Timeout (segundos)",
        ["pag.dinamico.dirs"] = "Directorios vigilados",
        ["pag.dinamico.capturar_red"] = "Capturar red",

        ["pag.intel.titulo"] = "Inteligencia de amenazas",
        ["pag.intel.subtitulo"] = "Consultas a VirusTotal, AbuseIPDB y AlienVault OTX",

        ["pag.muestras.titulo"] = "Muestras",
        ["pag.muestras.subtitulo"] = "Repositorio local catalogado de muestras analizadas",
        ["pag.muestras.buscar"] = "Buscar:",
        ["pag.muestras.familia"] = "Familia:",
        ["pag.muestras.riesgo_min"] = "Riesgo mín.:",
        ["pag.muestras.confirmar_eliminar"] = "¿Eliminar la muestra '{0}'?",

        ["pag.ml.titulo"] = "Clasificación inteligente",
        ["pag.ml.subtitulo"] = "k-NN sobre características estáticas y dinámicas, agrupamiento por similitud",

        ["pag.visual.titulo"] = "Visualización",
        ["pag.visual.subtitulo"] = "Visualizaciones generadas a partir del análisis estático real de un archivo",
        ["pag.visual.archivo"] = "Archivo:",
        ["pag.visual.de_repo"] = "De repositorio",
        ["pag.visual.analizar_visualizar"] = "Analizar y visualizar",
        ["pag.visual.modo"] = "Modo:",

        ["pag.plugins.titulo"] = "Plugins",
        ["pag.plugins.subtitulo"] = "Extensibilidad mediante DLLs que implementan IPluginMalyzer",

        ["pag.evasion.titulo"] = "Anti-evasión",
        ["pag.evasion.subtitulo"] = "Técnicas para evadir detecciones anti-VM/anti-debug y simulación de actividad humana",

        ["pag.urlscan.titulo"] = "URL Scan",
        ["pag.urlscan.subtitulo"] = "Análisis de URLs maliciosas con VirusTotal, URLhaus, PhishTank y heurísticas locales",

        ["pag.pro.titulo"] = "Herramientas profesionales",
        ["pag.pro.subtitulo"] = "Volcado de memoria, deobfuscación, extracción de configuración y emulación parcial",

        ["pag.sistema.titulo"] = "Sistema",
        ["pag.sistema.subtitulo"] = "Auditoría del sistema operativo: unidades, antivirus, persistencia, procesos, hosts y conexiones",
        ["pag.sistema.tab_unidades"] = "Unidades",
        ["pag.sistema.tab_proteccion"] = "Protección",
        ["pag.sistema.tab_inicio_carpetas"] = "Inicio (carpetas)",
        ["pag.sistema.tab_inicio_registro"] = "Inicio (Registro)",
        ["pag.sistema.tab_procesos"] = "Procesos",
        ["pag.sistema.tab_hosts"] = "Hosts",
        ["pag.sistema.tab_conexiones"] = "Conexiones",
        ["pag.sistema.menu.eliminar_entrada"] = "Eliminar entrada",
        ["pag.sistema.menu.eliminar_registro"] = "Eliminar del registro",
        ["pag.sistema.menu.matar_proceso"] = "Matar proceso",
        ["pag.sistema.menu.suspender"] = "Suspender proceso",
        ["pag.sistema.menu.reanudar"] = "Reanudar proceso",
        ["pag.sistema.menu.copiar"] = "Copiar",
        ["pag.sistema.menu.copiar_pid"] = "Copiar PID",
        ["pag.sistema.menu.volcar"] = "Volcar memoria",
        ["pag.sistema.menu.comentar"] = "Comentar entrada",
        ["pag.sistema.menu.cerrar_conexion"] = "Cerrar conexión",
        ["pag.sistema.menu.matar_dueno"] = "Matar proceso dueño",

        ["pag.netsniff.titulo"] = "Netsniff",
        ["pag.netsniff.subtitulo"] = "Captura de tráfico en vivo, análisis estadístico y detección por reglas",
        ["pag.netsniff.adaptador"] = "Adaptador:",
        ["pag.netsniff.iniciar"] = "Iniciar captura",
        ["pag.netsniff.exportar_pcap"] = "Exportar PCAP",
        ["pag.netsniff.tab_captura"] = "Captura",
        ["pag.netsniff.tab_filtros"] = "Filtros",
        ["pag.netsniff.tab_estadisticas"] = "Estadísticas",
        ["pag.netsniff.tab_alertas"] = "Alertas",

        ["dlg.confirmar"] = "Confirmar",
        ["dlg.confirmar_accion"] = "Confirmar acción",
        ["dlg.error"] = "Error",
        ["dlg.error_admin"] = "La operación falló. Probablemente necesités ejecutar Malyzer como administrador.",
        ["dlg.requiere_admin"] = "Requiere permisos de administrador.",

        ["acerca_de.titulo"] = "Acerca de Malyzer",
        ["acerca_de.descripcion"] = "Plataforma avanzada de análisis de malware con interfaz moderna",

        ["pdf.title.estatico"] = "Análisis estático",
        ["pdf.title.sistema"] = "Reporte del sistema",
        ["pdf.title.muestras"] = "Repositorio de muestras",
        ["pdf.title.netsniff"] = "Captura Netsniff",
        ["pdf.title.urlscan"] = "Análisis de URL",
        ["pdf.veredicto"] = "Veredicto",
        ["pdf.sin_veredicto"] = "(sin veredicto)",
        ["pdf.puntuacion_riesgo"] = "Puntuación de riesgo",
        ["pdf.hash_sha256"] = "Hash SHA-256",
        ["pdf.tamano"] = "Tamaño",
        ["pdf.entropia"] = "Entropía",
        ["pdf.bytes"] = "bytes",
        ["pdf.info_general"] = "Información general",
        ["pdf.archivo"] = "Archivo",
        ["pdf.tipo_detectado"] = "Tipo detectado",
        ["pdf.compilado"] = "Compilado",
        ["pdf.empacado"] = "Empacado",
        ["pdf.empacado_si"] = "sí",
        ["pdf.empacado_no"] = "no",
        ["pdf.arquitectura"] = "Arquitectura",
        ["pdf.secciones_pe"] = "Secciones PE",
        ["pdf.col_nombre"] = "Nombre",
        ["pdf.col_caracteristicas"] = "Características",
        ["pdf.imports_titulo"] = "Importaciones",
        ["pdf.imports_dlls"] = "DLLs",
        ["pdf.col_dll"] = "DLL",
        ["pdf.col_funciones"] = "Funciones",
        ["pdf.iocs_titulo"] = "Indicadores de compromiso (IOCs)",
        ["pdf.iocs_urls"] = "URLs",
        ["pdf.iocs_ips"] = "Direcciones IP",
        ["pdf.iocs_dominios"] = "Dominios",
        ["pdf.iocs_registro"] = "Claves de registro",
        ["pdf.iocs_rutas"] = "Rutas de archivo",
        ["pdf.yara_coincidencias"] = "Coincidencias YARA",
        ["pdf.yara_cadenas"] = "Cadenas",
        ["pdf.unidades_disco"] = "Unidades de disco",
        ["pdf.col_letra"] = "Letra",
        ["pdf.col_tipo"] = "Tipo",
        ["pdf.col_fs"] = "FS",
        ["pdf.col_total"] = "Total",
        ["pdf.col_libre"] = "Libre",
        ["pdf.col_uso"] = "Uso%",
        ["pdf.proteccion_titulo"] = "Software de protección",
        ["pdf.col_producto"] = "Producto",
        ["pdf.col_estado"] = "Estado",
        ["pdf.startup_carpetas"] = "Aplicaciones de inicio (carpetas)",
        ["pdf.col_origen"] = "Origen",
        ["pdf.col_comando"] = "Comando",
        ["pdf.startup_registro"] = "Inicio en el registro",
        ["pdf.col_clave"] = "Clave",
        ["pdf.procesos_titulo"] = "Procesos en ejecución",
        ["pdf.col_pid"] = "PID",
        ["pdf.col_memoria"] = "Memoria",
        ["pdf.col_hilos"] = "Hilos",
        ["pdf.col_ruta"] = "Ruta",
        ["pdf.hosts_titulo"] = "Archivo hosts",
        ["pdf.col_host"] = "Host",
        ["pdf.estado_sospechosa"] = "⚠ Sospechosa",
        ["pdf.conexiones_titulo"] = "Conexiones de red",
        ["pdf.col_proto"] = "Proto",
        ["pdf.col_local"] = "Local",
        ["pdf.col_remoto"] = "Remoto",
        ["pdf.muestras_catalogo"] = "Catálogo",
        ["pdf.muestras_total"] = "muestras",
        ["pdf.col_familia"] = "Familia",
        ["pdf.col_riesgo"] = "Riesgo",
        ["pdf.col_ingreso"] = "Ingreso",
        ["pdf.sin_clasificar"] = "(sin clasificar)",
        ["pdf.netsniff_paquetes"] = "paquetes capturados",
        ["pdf.netsniff_kpi_paquetes"] = "Paquetes",
        ["pdf.netsniff_kpi_bytes"] = "Bytes",
        ["pdf.netsniff_kpi_hosts"] = "Hosts únicos",
        ["pdf.netsniff_kpi_duracion"] = "Duración",
        ["pdf.netsniff_distribucion"] = "Distribución por protocolo",
        ["pdf.netsniff_paquetes_titulo"] = "Últimos paquetes",
        ["pdf.col_hora"] = "Hora",
        ["pdf.col_servicio"] = "Servicio",
        ["pdf.col_bytes_short"] = "Bytes",
        ["pdf.urlscan_url"] = "URL analizada",
        ["pdf.urlscan_resultado"] = "Resultado del análisis",
        ["pdf.urlscan_consenso"] = "Consenso de motores",
        ["pdf.urlscan_motores"] = "Motores antivirus",
        ["pdf.urlscan_categoria"] = "Categoría",
        ["pdf.urlscan_metadata"] = "Información técnica",
        ["pdf.footer_generado"] = "Reporte generado automáticamente",
        ["pdf.pagina"] = "Página",
        ["pdf.pagina_de"] = "de",

        ["btn.cargar_archivo"] = "Cargar archivo",
        ["btn.exportar_reporte"] = "Exportar reporte",
        ["btn.exportar_pdf"] = "Exportar PDF",
        ["btn.guardar_cambios"] = "Guardar cambios",
        ["btn.aplicar_filtros"] = "Aplicar filtros",
        ["btn.aplicar_blacklist"] = "Aplicar lista negra",
        ["btn.probar_ejecucion"] = "Probar ejecución",
        ["btn.volcar_memoria"] = "Volcar memoria",

        ["col.nombre"] = "Nombre",
        ["col.tipo"] = "Tipo",
        ["col.tamano"] = "Tamaño",
        ["col.familia"] = "Familia",
        ["col.riesgo"] = "Riesgo",
        ["col.estado"] = "Estado",
        ["col.proceso"] = "Proceso",
        ["col.memoria"] = "Memoria",
        ["col.direccion"] = "Dirección",
        ["col.operacion"] = "Operación",
        ["col.linea_comando"] = "Línea de comando",
        ["col.accion"] = "Acción",
        ["col.entropia"] = "Entropía",
        ["col.sospechosa"] = "Sospechosa",
        ["col.caracteristicas"] = "Características",
        ["col.tamano_virtual"] = "Tamaño virtual",
        ["col.tamano_crudo"] = "Tamaño crudo",
        ["col.categoria"] = "Categoría",

        ["pag.estatico.subtitulo"] = "Inspección profunda de PE, strings, IOCs, packers y reglas YARA",
        ["pag.estatico.no_pe"] = "No hay cabecera PE disponible para este archivo.",
        ["pag.estatico.riesgo"] = "Riesgo: ",
        ["pag.estatico.tipo_magico"] = "Tipo mágico",
        ["pag.estatico.tipo_maquina"] = "Tipo de máquina",
        ["pag.estatico.tipo_ejecutable"] = "Tipo ejecutable",
        ["pag.estatico.num_secciones"] = "Núm. secciones",
        ["pag.estatico.punto_entrada"] = "Punto de entrada",
        ["pag.estatico.base_imagen"] = "Base de imagen",
        ["pag.estatico.entropia_total"] = "Entropía total",

        ["pag.dinamico.subtitulo"] = "Sandbox local con monitoreo de procesos, archivos, registro y red",

        ["pag.intel.iocs_help"] = "Podés pegar varios IOCs separados por coma o salto de línea",
        ["pag.intel.puntuacion_global"] = "Puntuación global",
        ["pag.intel.reputacion"] = "reputación",

        ["pag.muestras.guardar"] = "Guardar cambios",
        ["pag.muestras.eliminar"] = "Eliminar",
        ["pag.muestras.exportar"] = "Exportar",
        ["pag.muestras.sin_seleccion"] = "Sin selección",
        ["pag.muestras.riesgo_critico"] = "80+ crítico",

        ["pag.ml.caract_extraidas"] = "Características extraídas",
        ["pag.ml.familia_predicha"] = "Familia predicha",
        ["pag.ml.sin_datos"] = "Sin datos. Seleccioná un archivo y clasificalo.",
        ["pag.ml.sin_clasificacion"] = "Sin clasificación todavía.",
        ["pag.ml.distribucion_probs"] = "Distribución de probabilidades",
        ["pag.ml.vecinos"] = "Vecinos más cercanos",

        ["pag.visual.modo.entropia"] = "Mapa de entropía por sección",
        ["pag.visual.modo.imports"] = "Distribución de imports por DLL",
        ["pag.visual.modo.iocs"] = "Grafo de IOCs detectados",
        ["pag.visual.modo.histograma"] = "Histograma de bytes",
        ["pag.visual.modo.strings"] = "Mapa de strings sospechosas",
        ["pag.visual.modo.layout"] = "Layout de secciones PE",
        ["pag.visual.modo.arbol"] = "Árbol de procesos del sistema",

        ["pag.plugins.como_crear"] = "¿Cómo crear un plugin?",
        ["pag.plugins.entrada_prueba"] = "entrada de prueba",
        ["pag.plugins.salida_prueba"] = "Salida de prueba",
        ["pag.plugins.descripcion_etiqueta"] = "Descripción",
        ["pag.plugins.version_etiqueta"] = "Versión",

        ["pag.pro.tab_dump"] = "Volcar memoria",
        ["pag.pro.tab_deobfusc"] = "Deobfuscación",
        ["pag.pro.tab_extract"] = "Extracción de config",
        ["pag.pro.tab_emulation"] = "Emulación",
        ["pag.pro.bytes_help"] = "Pegá bytes en hex (separados por espacio o sin separador):",
        ["pag.pro.tecnica"] = "Técnica",
        ["pag.pro.puntuacion"] = "Puntuación",

        ["pag.sistema.menu.copiar_nombre"] = "Copiar nombre",
        ["pag.sistema.menu.copiar_remoto"] = "Copiar dirección remota",
        ["pag.sistema.menu.copiar_local"] = "Copiar dirección local",
        ["pag.sistema.menu.bloquear_ip"] = "Bloquear IP en firewall (Windows)",
        ["pag.sistema.menu.abrir_ubicacion_ejec"] = "Abrir ubicación del ejecutable",
        ["pag.sistema.menu.abrir_ubicacion"] = "Abrir ubicación",

        ["pag.netsniff.lista_negra"] = "Lista negra de IPs",
        ["pag.netsniff.lista_negra_help"] = "Una IP por línea. Los paquetes a/desde estas IPs se resaltan como alerta.",
        ["pag.netsniff.por_protocolo"] = "Por protocolo",
        ["pag.netsniff.trafico_60"] = "Tráfico (últimos 60 s)",
        ["pag.netsniff.ocultar_local"] = "Ocultar tráfico local",
        ["pag.netsniff.sin_alertas"] = "Sin alertas todavía",
        ["pag.netsniff.kpi.trafico"] = "Tráfico",
        ["pag.netsniff.kpi.duracion"] = "Duración",
        ["pag.netsniff.kpi.hosts"] = "Hosts únicos",

        ["pag.urlscan.tab_motores"] = "Motores",
        ["pag.urlscan.tab_heuristicas"] = "Heurísticas",
        ["pag.urlscan.tab_info"] = "Información",
        ["pag.urlscan.tab_fuentes"] = "Fuentes / errores",
        ["pag.urlscan.kpi.maliciosos"] = "Maliciosos",
        ["pag.urlscan.kpi.sospechosos"] = "Sospechosos",
        ["pag.urlscan.kpi.limpios"] = "Limpios",
        ["pag.urlscan.kpi.sin_deteccion"] = "Sin detección",
        ["pag.urlscan.servicios_consultados"] = "Servicios consultados",
        ["pag.urlscan.avisos_errores"] = "Avisos / errores",

        ["pag.inicio.importar_muestra"] = "Importar muestra",
        ["pag.inicio.sin_muestras"] = "Sin muestras catalogadas todavía. Importá archivos para empezar.",

        ["acerca_de.tecnologias"] = "Tecnologías",
        ["acerca_de.version"] = "Versión 1.0.0",

        ["msg.cargando_plugins"] = "Cargando plugins...",
        ["msg.cargando_config"] = "Cargando configuración...",
        ["msg.inicializando_bd"] = "Inicializando base de datos...",
        ["msg.conectando_intel"] = "Conectando servicios de inteligencia...",
        ["msg.idioma_cambiado"] = "Idioma cambiado a Español",
        ["msg.config_guardada"] = "Configuración guardada",
        ["msg.config_restablecida"] = "Configuración restablecida",
        ["msg.confirmar_reset"] = "¿Restablecer todos los valores por defecto?",
        ["msg.error_admin"] = "La operación falló. Probablemente necesités ejecutar Malyzer como administrador.",
        ["msg.requiere_admin"] = "¿Estás ejecutando como administrador?",
        ["msg.confirmar_accion"] = "Confirmar acción",
        ["msg.confirmar_eliminar"] = "Confirmar eliminación",
        ["msg.adv_seguridad"] = "Advertencia de seguridad",
        ["msg.continuar"] = "¿Continuar?",
        ["msg.error"] = "Error",
        ["msg.exito"] = "Éxito",
        ["msg.archivo_no_encontrado"] = "Archivo no encontrado en disco.",
        ["msg.sin_seleccion"] = "Sin selección",
        ["msg.no_muestras"] = "No hay muestras en el repositorio.",
        ["msg.no_muestras_repo"] = "No hay muestras en el repositorio. Importá alguna primero desde la página Muestras.",
        ["msg.no_muestras_export"] = "No hay muestras para exportar.",
        ["msg.ingresar_url"] = "Ingresá una URL para analizar.",
        ["msg.no_browser"] = "No se pudo abrir el navegador",
        ["msg.pdf_exportado"] = "PDF exportado",
        ["msg.pdf_abrir"] = "PDF exportado. ¿Abrirlo ahora?",
        ["msg.pdf_correcto_abrir"] = "PDF exportado correctamente. ¿Abrirlo ahora?",
        ["msg.estatico_progreso"] = "Análisis estático en curso",
        ["msg.estatico_completo"] = "Análisis estático completado",
        ["msg.estatico_archivo_listo"] = "Archivo cargado, listo para analizar",
        ["msg.estatico_error"] = "Error en análisis",
        ["msg.dinamico_finalizado"] = "Análisis dinámico finalizado",
        ["msg.dinamico_error"] = "Error en análisis dinámico",
        ["msg.url_analizando"] = "Analizando URL en múltiples servicios...",
        ["msg.url_completo"] = "Análisis completo",
        ["msg.url_no_heur"] = "No se detectaron heurísticas sospechosas locales.",
        ["msg.url_categoria_prefix"] = "Categoría: ",
        ["msg.captura_inicia"] = "Primero iniciá una captura.",
        ["msg.captura_seleccionar"] = "Seleccioná un adaptador.",
        ["msg.captura_curso"] = "Captura en curso",
        ["msg.no_proc_dueno"] = "No se pudo resolver el PID del proceso.",
        ["msg.no_proc_conexion"] = "No se pudo resolver el proceso dueño de la conexión.\n\nProbá con \"Matar proceso dueño\" o ejecutá Malyzer como administrador.",
        ["msg.no_firewall"] = "No se pudo agregar la regla. ¿Estás ejecutando como administrador?",
        ["msg.firewall_aplicada"] = "Regla agregada al firewall para",
        ["msg.proc_terminado"] = "terminado",
        ["msg.proc_suspendido"] = "suspendido",
        ["msg.proc_reanudado"] = "reanudado",
        ["msg.host_comentado"] = "Línea comentada en hosts",
        ["msg.host_eliminado"] = "Línea eliminada de hosts",
        ["msg.reg_eliminado"] = "Entrada de registro eliminada",
        ["msg.entrada_eliminada"] = "Entrada eliminada",
        ["msg.inspeccion_progreso"] = "Inspeccionando sistema...",
        ["msg.inspeccion_completa"] = "Inspección completa",
        ["msg.inspeccion_error"] = "Error inspeccionando sistema",
        ["msg.dump_progreso"] = "Volcando memoria...",
        ["msg.dump_titulo"] = "Guardar volcado de memoria",
        ["msg.confirmar_matar"] = "¿Matar el proceso",
        ["msg.confirmar_matar_dueno"] = "¿Matar el proceso dueño de",
        ["msg.confirmar_eliminar_archivo"] = "¿Eliminar el archivo de inicio?",
        ["msg.confirmar_eliminar_reg"] = "¿Eliminar la entrada del registro?",
        ["msg.confirmar_comentar_linea"] = "¿Comentar la línea",
        ["msg.confirmar_eliminar_linea"] = "¿Eliminar la línea",
        ["msg.confirmar_bloquear"] = "¿Crear regla de firewall para bloquear todas las conexiones salientes a",
        ["msg.confirmar_bloquear_admin"] = "Requiere permisos de administrador.",
        ["msg.confirmar_cerrar_conex"] = "Para cerrar la conexión hay que terminar el proceso dueño",
        ["msg.confirmar_eliminar_muestra"] = "¿Eliminar la muestra",
        ["msg.importadas"] = "Importadas",
        ["msg.muestras_count"] = "muestra(s)",
        ["msg.muestras_errores"] = "errores",
        ["msg.error_cargando_muestras"] = "Error cargando muestras",
        ["msg.exportado_a"] = "Exportado a",
        ["msg.adv_dinamico"] = "Vas a ejecutar la muestra. Asegurate de estar en un entorno aislado (VM/sandbox).",
        ["msg.import_titulo"] = "Importar muestras",
        ["msg.import_titulo_uno"] = "Importar muestra",
        ["msg.export_titulo_muestra"] = "Exportar muestra",
        ["msg.export_titulo_muestras_pdf"] = "Exportar muestras a PDF",
        ["msg.export_titulo_pcap"] = "Exportar captura a PCAP",
        ["msg.export_titulo_estatico"] = "Exportar reporte a PDF",
        ["msg.export_titulo_sistema"] = "Exportar reporte de sistema",
        ["msg.export_titulo_netsniff"] = "Exportar reporte de Netsniff",
        ["msg.export_titulo_url"] = "Exportar análisis de URL a PDF",
        ["msg.export_titulo_estatico_txt"] = "Exportar reporte",
        ["msg.filtro_pdf"] = "PDF (*.pdf)|*.pdf",
        ["msg.filtro_pcap"] = "Captura PCAP (*.pcap)|*.pcap",
        ["msg.filtro_dump"] = "Mini-dump (*.dmp)|*.dmp",
        ["msg.filtro_todos"] = "Todos los archivos (*.*)|*.*",
        ["msg.filtro_ejecutables"] = "Archivos ejecutables y otros (*.*)|*.*",
        ["msg.filtro_yara"] = "Carpeta con reglas YARA (.yar)",
        ["msg.kpi_total"] = "Base de datos",
        ["msg.kpi_critico"] = "CRÍTICO",
        ["msg.kpi_minimo"] = "MÍNIMO",
        ["msg.proc_pid"] = "Proceso PID",
        ["msg.conexion_cerrada"] = "conexión cerrada",
        ["msg.viz_lista"] = "Visualización lista",
        ["msg.viz_no_pe"] = "El archivo no tiene secciones PE (¿no es un PE?)",
        ["msg.viz_sin_secciones"] = "Sin secciones (no es un PE válido)",
        ["msg.viz_sin_imports"] = "El archivo no tiene importaciones.",
        ["msg.viz_sin_iocs"] = "No se detectaron IOCs en el archivo.",
        ["msg.viz_sin_strings"] = "No se hallaron strings con palabras clave conocidas.",
        ["msg.viz_no_proc"] = "No se pudo enumerar procesos del sistema.",
        ["msg.viz_analizando"] = "Analizando para visualización...",
        ["msg.viz_seleccionar_muestra"] = "Seleccionar muestra del repositorio",
        ["msg.url_validar"] = "Servicios consultados",
        ["msg.url_sin_meta"] = "Sin metadatos disponibles.",
        ["msg.url_sin_fuentes"] = "(ninguna)",
        ["msg.url_sin_errores"] = "(sin errores)",
        ["msg.cls_completo"] = "Clasificación completada",
        ["msg.cls_grupos_completo"] = "Agrupamiento completado",
        ["msg.cls_agrupando"] = "Agrupando muestras del repositorio...",
        ["msg.url_sin_externas"] = "Sin fuentes externas (configurá API keys en Configuración)",
        ["msg.url_fuentes_prefix"] = "Fuentes: ",

        ["veredicto.alto"] = "Alto riesgo · Probablemente malicioso",
        ["veredicto.medio"] = "Riesgo medio · Sospechoso",
        ["veredicto.bajo"] = "Bajo riesgo · Anomalías detectadas",
        ["veredicto.limpio"] = "Limpio · Sin indicadores claros",
        ["tipo.pe"] = "PE / Ejecutable Windows",
        ["tipo.elf"] = "ELF / Ejecutable Linux",
        ["tipo.macho64"] = "Mach-O 64-bit",
        ["tipo.macho32"] = "Mach-O 32-bit",
        ["tipo.zip"] = "Archivo ZIP / OOXML / JAR",
        ["tipo.rar"] = "Archivo RAR",
        ["tipo.7z"] = "Archivo 7-Zip",
        ["tipo.pdf"] = "Documento PDF",
        ["tipo.ole"] = "Documento OLE / Office antiguo",
        ["tipo.script"] = "Script (shebang)",
        ["tipo.cab"] = "Microsoft Cabinet",
        ["tipo.binario"] = "datos binarios",
        ["tipo.desconocido"] = "desconocido",

        ["yara.upx.titulo"] = "Marcador de empacador UPX",
        ["yara.antivm.titulo"] = "Técnicas anti-VM y anti-debug",
        ["yara.injection.titulo"] = "APIs de inyección de procesos",
        ["yara.powershell.titulo"] = "Ejecución de PowerShell codificado",
        ["yara.browsers.titulo"] = "Acceso a perfiles y datos de navegadores",
        ["yara.persistence.titulo"] = "Claves de registro usadas para persistencia",
        ["yara.keylogger.titulo"] = "APIs típicas de keyloggers",
        ["yara.mimikatz.titulo"] = "Cadenas típicas de Mimikatz",
        ["yara.ransomware.titulo"] = "Indicadores genéricos de ransomware",
        ["yara.antianalysis.titulo"] = "Sospechoso · técnicas anti-análisis",

        ["pag.adv.titulo"] = "Inteligencia avanzada",
        ["pag.adv.subtitulo"] = "Diff de muestras, mapeo MITRE ATT&CK, decodificación con Capstone, ETW dinámico y triaje con LLM",
        ["pag.adv.tab_diff"] = "Diff de muestras",
        ["pag.adv.tab_mitre"] = "MITRE ATT&CK",
        ["pag.adv.tab_decoder"] = "Decoder (Capstone)",
        ["pag.adv.tab_etw"] = "ETW dinámico",
        ["pag.adv.tab_multi"] = "Multi-formato",
        ["pag.adv.multi_help"] = "Análisis profundo multi-formato. Detecta automáticamente el tipo de archivo (PE, APK, Office, PDF, scripts, JAR) y aplica análisis específico para cada uno: permisos peligrosos, macros VBA, JavaScript en PDFs, ejecución dinámica en scripts, etc.",
        ["pag.adv.multi_analizar"] = "Analizar archivo",
        ["pag.adv.diff_help"] = "Compará dos muestras: SSDeep, imports comunes, secciones, reglas YARA y IOCs. Útil para detectar variantes de la misma familia.",
        ["pag.adv.diff_comparar"] = "Comparar A vs B",
        ["pag.adv.diff_buscar_similares"] = "Buscar similares en repo",
        ["pag.adv.diff_indexar"] = "Indexar SSDeep en repo",
        ["pag.adv.mitre_help"] = "Mapeo automático de técnicas MITRE ATT&CK basado en imports, YARA, IOCs y comportamiento.",
        ["pag.adv.mitre_mapear"] = "Mapear",
        ["pag.adv.decoder_help"] = "Disassembly con Capstone para detectar stack strings, loops XOR, API hashing y otras técnicas de obfuscación.",
        ["pag.adv.decoder_decodificar"] = "Decodificar",
        ["pag.adv.etw_help"] = "Tracing en tiempo real vía Event Tracing for Windows. Capturá file/registry/network/process events de un proceso y sus hijos. Requiere admin.",
        ["pag.adv.etw_total"] = "Eventos",
        ["pag.adv.etw_archivos"] = "Archivos",
        ["pag.adv.etw_registro"] = "Registro",
        ["pag.adv.etw_red"] = "Red",
        ["pag.adv.etw_procesos"] = "Procesos",


        ["pag.netsniff.menu_geoip"] = "🌍 Inspeccionar IP (GeoIP / WHOIS)",
        ["pag.netsniff.menu_copiar_ip"] = "Copiar IP remota",
        ["pag.netsniff.menu_virustotal"] = "Buscar en VirusTotal",
        ["pag.netsniff.menu_abuseipdb"] = "Buscar en AbuseIPDB",
        ["pag.netsniff.menu_shodan"] = "Buscar en Shodan",

        ["btn.detener"] = "Detener",
        ["btn.listar_procesos"] = "Listar procesos",
        ["btn.agrupar_repo"] = "Agrupar repositorio",
        ["btn.clasificar"] = "Clasificar",
        ["btn.seleccionar"] = "Seleccionar",
        ["btn.abrir_directorio"] = "Abrir directorio",
        ["btn.abrir_archivo_hosts"] = "Abrir archivo hosts",
        ["btn.copiar_ruta"] = "Copiar ruta",

        ["lbl.archivo"] = "Archivo:",
        ["lbl.archivo_simple"] = "Archivo",
        ["lbl.ruta"] = "Ruta",
        ["lbl.comando_ruta"] = "Comando / Ruta",
        ["lbl.esperando_archivo"] = "Esperando archivo",
        ["lbl.sin_archivo"] = "(sin archivo cargado)",
        ["lbl.auto_detectar"] = "auto-detectar",
        ["lbl.muestras_count_lower"] = "muestras",

        ["pag.pro.advertencia_volcado"] = "Esta función produce un volcado FULL de memoria. Solo usar en máquina virtual con permisos administrativos. Los volcados pueden ser muy grandes (GB).",
        ["pag.ml.modelo_entrenado"] = "Modelo entrenado con {0} ejemplos",
        ["pag.ml.agrupamiento_grupos"] = "Agrupamiento por similitud: {0} grupos",
        ["pag.acerca.advertencia_titulo"] = "⚠ ADVERTENCIA",
        ["pag.acerca.advertencia_texto"] = "Esta herramienta ejecuta y analiza muestras de malware. Usar siempre en máquinas virtuales aisladas con snapshots y red restringida. No ejecutar muestras en sistemas de producción.",

        // ───── v1.1 ─────
        ["pag.intel.tab_lookup"] = "Consulta de IOCs",
        ["pag.intel.tab_upload"] = "Subir muestra",
        ["pag.intel.usar_mb"] = "Consultar MalwareBazaar",
        ["pag.intel.usar_tf"] = "Consultar ThreatFox",
        ["pag.intel.upload_titulo"] = "Subir muestra a servicio de análisis",
        ["pag.intel.upload_aviso"] = "Subir una muestra a VirusTotal o MalwareBazaar la hace pública para la comunidad de threat intel. Solo subí muestras que querés compartir.",
        ["pag.intel.upload_archivo"] = "Archivo a subir",
        ["pag.intel.upload_destino"] = "Destinos",
        ["pag.intel.upload_vt"] = "VirusTotal (requiere clave de API)",
        ["pag.intel.upload_mb"] = "MalwareBazaar (requiere clave de abuse.ch)",
        ["pag.intel.upload_meta"] = "Metadatos opcionales (MalwareBazaar)",
        ["pag.intel.upload_etiquetas"] = "Etiquetas",
        ["pag.intel.upload_comentario"] = "Comentario",
        ["pag.intel.upload_publico"] = "Subida pública (visible para la comunidad)",
        ["btn.subir"] = "Subir muestra",
        ["btn.exportar_pdf"] = "Exportar PDF",
        ["estado.subiendo"] = "Subiendo muestra...",
        ["estado.subida_completada"] = "Subida completada",
        ["estado.subida_cancelada"] = "Subida cancelada",
        ["msg.confirmar_subida"] = "Estás por subir esta muestra a un servicio público de análisis. Quedará accesible por la comunidad. ¿Continuar?",
        ["msg.elegir_muestra"] = "Elegir muestra",
        ["msg.elegir_muestra_primero"] = "Primero elegí un archivo a subir",
        ["msg.elegir_destino_subida"] = "Tenés que elegir al menos un destino",
        ["msg.vt_sin_clave"] = "VirusTotal: clave de API no configurada (Configuración → Claves de API)",
        ["msg.mb_sin_clave"] = "MalwareBazaar: clave de abuse.ch no configurada",
        ["msg.sin_resultados"] = "No hay resultados para exportar",
        ["msg.sin_subidas"] = "No hay subidas para exportar",
        ["msg.guardar_pdf_intel"] = "Guardar reporte de Threat Intel",
        ["msg.guardar_pdf_subidas"] = "Guardar reporte de Subidas",
        ["pag.estatico.tab_firma"] = "Firma digital",
        ["pag.estatico.firma_titulo"] = "Verificación Authenticode",
        ["pag.estatico.firma_estado"] = "Estado",
        ["pag.estatico.firma_sujeto"] = "Sujeto",
        ["pag.estatico.firma_emisor"] = "Emisor",
        ["pag.estatico.firma_emision"] = "Emitido",
        ["pag.estatico.firma_vencimiento"] = "Vencimiento",
        ["pag.estatico.firma_algoritmo"] = "Algoritmo",
        ["pag.estatico.firma_huella"] = "Huella (SHA-1)",
        ["pag.estatico.firma_serie"] = "Número de serie",
        ["pag.estatico.firma_chequeo"] = "Chequeos",
        ["pag.estatico.rich_titulo"] = "Rich Header (metadatos del compilador)",
        ["pag.estatico.rich_presente"] = "Presente",
        ["pag.estatico.rich_compilador"] = "Compilador estimado",
        ["pag.estatico.rich_producto"] = "Producto",
        ["pdf.title.intel"] = "Reporte de Threat Intel",
        ["pdf.title.subidas"] = "Reporte de subidas",
        ["pdf.title.multiformato"] = "Análisis multi-formato",
        ["pdf.intel_total"] = "indicadores",
        ["pdf.intel_kpi_total"] = "Indicadores",
        ["pdf.intel_kpi_global"] = "Score global",
        ["pdf.intel_kpi_alta"] = "Reputación alta",
        ["pdf.intel_kpi_media"] = "Reputación media",
        ["pdf.intel_resumen"] = "Puntuación global ponderada",
        ["pdf.intel_por_fuente"] = "Distribución por fuente",
        ["pdf.intel_indicadores"] = "Indicadores consultados",
        ["pdf.col_fuente"] = "Fuente",
        ["pdf.col_valor"] = "Valor",
        ["pdf.col_reputacion"] = "Reputación",
        ["pdf.col_detalles"] = "Detalles",
        ["pdf.col_descripcion"] = "Descripción",
        ["pdf.col_severidad"] = "Severidad",
        ["pdf.col_tamano"] = "Tamaño",
        ["pdf.subidas_total"] = "subidas",
        ["pdf.subidas_kpi_total"] = "Total",
        ["pdf.subidas_kpi_exitosas"] = "Exitosas",
        ["pdf.subidas_kpi_existentes"] = "Ya existentes",
        ["pdf.subidas_kpi_errores"] = "Con error",
        ["pdf.subidas_detecciones"] = "Detecciones",
        ["pdf.multi_kpi_indicadores"] = "Indicadores",
        ["pdf.metadata"] = "Metadatos",
        ["pdf.indicadores"] = "Indicadores detectados",
        ["pdf.strings_relevantes"] = "Strings relevantes",
        ["pdf.veredicto"] = "Veredicto",
    };

    private static Dictionary<string, string> DiccionarioEn() => new()
    {
        ["nav.inicio"] = "Dashboard",
        ["nav.estatico"] = "Static analysis",
        ["nav.dinamico"] = "Dynamic sandbox",
        ["nav.pro"] = "Pro tools",
        ["nav.intel"] = "Threat Intel",
        ["nav.ml"] = "ML classification",
        ["nav.visual"] = "Visualization",
        ["nav.muestras"] = "Samples",
        ["nav.plugins"] = "Plugins",
        ["nav.evasion"] = "Anti-evasion",
        ["nav.urlscan"] = "URL Scan",
        ["nav.advanced"] = "Advanced intel",
        ["nav.sistema"] = "System",
        ["nav.netsniff"] = "Netsniff",
        ["nav.config"] = "Settings",
        ["nav.grupo.analisis"] = "ANALYSIS",
        ["nav.grupo.inteligencia"] = "INTELLIGENCE",
        ["nav.grupo.gestion"] = "MANAGEMENT",
        ["nav.grupo.monitoreo"] = "MONITORING",

        ["estado.listo"] = "Ready",
        ["estado.trabajando"] = "Working...",
        ["estado.error"] = "Error",
        ["estado.muestras"] = "samples",

        ["btn.guardar"] = "Save changes",
        ["btn.cancelar"] = "Cancel",
        ["btn.aplicar"] = "Apply",
        ["btn.refrescar"] = "Refresh",
        ["btn.refrescar_todo"] = "Refresh all",
        ["btn.examinar"] = "Browse",
        ["btn.eliminar"] = "Delete",
        ["btn.exportar"] = "Export",
        ["btn.importar"] = "Import",
        ["btn.iniciar"] = "Start",
        ["btn.analizar"] = "Analyze",
        ["btn.consultar"] = "Query",
        ["btn.limpiar"] = "Clear",
        ["btn.recargar"] = "Reload",
        ["btn.restablecer"] = "Reset",
        ["btn.regenerar"] = "Regenerate",

        ["pag.config.titulo"] = "Settings",
        ["pag.config.subtitulo"] = "API keys, paths to external tools, language and runtime options",
        ["pag.config.idioma"] = "Interface language",
        ["pag.config.idioma_descripcion"] = "Changes apply instantly in most screens",
        ["pag.config.api"] = "API keys",
        ["pag.config.rutas"] = "External tool paths",
        ["pag.config.sandbox"] = "Sandbox and dynamic analysis",
        ["pag.config.sandbox_aislada"] = "Use isolated sandbox (recommended)",
        ["pag.config.enviar_vt"] = "Allow uploading samples to VirusTotal",
        ["pag.config.timeout"] = "Dynamic timeout (s)",
        ["pag.config.almacenamiento"] = "Storage",
        ["pag.config.dir_datos"] = "Data directory",
        ["pag.config.bd"] = "Database",
        ["pag.config.abrir_dir_datos"] = "Open data directory",
        ["pag.config.abrir_dir_reportes"] = "Open reports directory",
        ["pag.config.guardado"] = "Settings saved",
        ["pag.config.confirmar_reset"] = "Reset all values to defaults?",
        ["pag.config.reglas_yara"] = "YARA rules",

        ["pag.inicio.titulo"] = "Home",
        ["pag.inicio.subtitulo"] = "Lab overview",
        ["pag.inicio.muestras_totales"] = "Total samples",
        ["pag.inicio.riesgo_alto"] = "High risk",
        ["pag.inicio.familias"] = "Detected families",
        ["pag.inicio.pendientes"] = "Pending analysis",
        ["pag.inicio.distribucion"] = "Distribution by family",
        ["pag.inicio.recientes"] = "Recent samples",
        ["pag.inicio.acciones"] = "Quick actions",
        ["pag.inicio.entorno"] = "Environment status",
        ["pag.inicio.importar_muestras"] = "Import samples",
        ["pag.inicio.lab_operativo"] = "Lab online · Ready to analyze",

        ["pag.estatico.titulo"] = "Static analysis",
        ["pag.estatico.cargar"] = "Load file",
        ["pag.estatico.veredicto"] = "Verdict",
        ["pag.estatico.tab_general"] = "General",
        ["pag.estatico.tab_pe"] = "PE header",
        ["pag.estatico.tab_secciones"] = "Sections",
        ["pag.estatico.tab_imports"] = "Imports",
        ["pag.estatico.tab_strings"] = "Strings",
        ["pag.estatico.tab_iocs"] = "IOCs",
        ["pag.estatico.tab_yara"] = "YARA",

        ["pag.dinamico.titulo"] = "Dynamic sandbox",
        ["pag.dinamico.advertencia"] = "Run only in an isolated VM with a snapshot",
        ["pag.dinamico.timeout"] = "Timeout (seconds)",
        ["pag.dinamico.dirs"] = "Watched directories",
        ["pag.dinamico.capturar_red"] = "Capture network",

        ["pag.intel.titulo"] = "Threat intelligence",
        ["pag.intel.subtitulo"] = "Queries against VirusTotal, AbuseIPDB and AlienVault OTX",

        ["pag.muestras.titulo"] = "Samples",
        ["pag.muestras.subtitulo"] = "Local catalogued repository of analyzed samples",
        ["pag.muestras.buscar"] = "Search:",
        ["pag.muestras.familia"] = "Family:",
        ["pag.muestras.riesgo_min"] = "Min. risk:",
        ["pag.muestras.confirmar_eliminar"] = "Delete sample '{0}'?",

        ["pag.ml.titulo"] = "Smart classification",
        ["pag.ml.subtitulo"] = "k-NN over static and dynamic features, similarity clustering",

        ["pag.visual.titulo"] = "Visualization",
        ["pag.visual.subtitulo"] = "Visualizations generated from real static analysis of a file",
        ["pag.visual.archivo"] = "File:",
        ["pag.visual.de_repo"] = "From repository",
        ["pag.visual.analizar_visualizar"] = "Analyze and visualize",
        ["pag.visual.modo"] = "Mode:",

        ["pag.plugins.titulo"] = "Plugins",
        ["pag.plugins.subtitulo"] = "Extensibility via DLLs implementing IPluginMalyzer",

        ["pag.evasion.titulo"] = "Anti-evasion",
        ["pag.evasion.subtitulo"] = "Techniques to evade anti-VM/anti-debug detections and simulate human activity",

        ["pag.urlscan.titulo"] = "URL Scan",
        ["pag.urlscan.subtitulo"] = "Analyze malicious URLs against VirusTotal, URLhaus, PhishTank and local heuristics",

        ["pag.pro.titulo"] = "Pro tools",
        ["pag.pro.subtitulo"] = "Memory dump, deobfuscation, config extraction and partial emulation",

        ["pag.sistema.titulo"] = "System",
        ["pag.sistema.subtitulo"] = "OS audit: drives, antivirus, persistence, processes, hosts and connections",
        ["pag.sistema.tab_unidades"] = "Drives",
        ["pag.sistema.tab_proteccion"] = "Protection",
        ["pag.sistema.tab_inicio_carpetas"] = "Startup (folders)",
        ["pag.sistema.tab_inicio_registro"] = "Startup (Registry)",
        ["pag.sistema.tab_procesos"] = "Processes",
        ["pag.sistema.tab_hosts"] = "Hosts",
        ["pag.sistema.tab_conexiones"] = "Connections",
        ["pag.sistema.menu.eliminar_entrada"] = "Delete entry",
        ["pag.sistema.menu.eliminar_registro"] = "Delete from registry",
        ["pag.sistema.menu.matar_proceso"] = "Kill process",
        ["pag.sistema.menu.suspender"] = "Suspend process",
        ["pag.sistema.menu.reanudar"] = "Resume process",
        ["pag.sistema.menu.copiar"] = "Copy",
        ["pag.sistema.menu.copiar_pid"] = "Copy PID",
        ["pag.sistema.menu.volcar"] = "Dump memory",
        ["pag.sistema.menu.comentar"] = "Comment entry",
        ["pag.sistema.menu.cerrar_conexion"] = "Close connection",
        ["pag.sistema.menu.matar_dueno"] = "Kill owner process",

        ["pag.netsniff.titulo"] = "Netsniff",
        ["pag.netsniff.subtitulo"] = "Live traffic capture, statistical analysis and rule-based detection",
        ["pag.netsniff.adaptador"] = "Adapter:",
        ["pag.netsniff.iniciar"] = "Start capture",
        ["pag.netsniff.exportar_pcap"] = "Export PCAP",
        ["pag.netsniff.tab_captura"] = "Capture",
        ["pag.netsniff.tab_filtros"] = "Filters",
        ["pag.netsniff.tab_estadisticas"] = "Statistics",
        ["pag.netsniff.tab_alertas"] = "Alerts",

        ["dlg.confirmar"] = "Confirm",
        ["dlg.confirmar_accion"] = "Confirm action",
        ["dlg.error"] = "Error",
        ["dlg.error_admin"] = "Operation failed. You probably need to run Malyzer as administrator.",
        ["dlg.requiere_admin"] = "Requires administrator privileges.",

        ["acerca_de.titulo"] = "About Malyzer",
        ["acerca_de.descripcion"] = "Advanced malware analysis platform with modern interface",

        ["pdf.title.estatico"] = "Static analysis",
        ["pdf.title.sistema"] = "System report",
        ["pdf.title.muestras"] = "Sample repository",
        ["pdf.title.netsniff"] = "Netsniff capture",
        ["pdf.title.urlscan"] = "URL analysis",
        ["pdf.veredicto"] = "Verdict",
        ["pdf.sin_veredicto"] = "(no verdict)",
        ["pdf.puntuacion_riesgo"] = "Risk score",
        ["pdf.hash_sha256"] = "SHA-256 hash",
        ["pdf.tamano"] = "Size",
        ["pdf.entropia"] = "Entropy",
        ["pdf.bytes"] = "bytes",
        ["pdf.info_general"] = "General information",
        ["pdf.archivo"] = "File",
        ["pdf.tipo_detectado"] = "Detected type",
        ["pdf.compilado"] = "Compiled",
        ["pdf.empacado"] = "Packed",
        ["pdf.empacado_si"] = "yes",
        ["pdf.empacado_no"] = "no",
        ["pdf.arquitectura"] = "Architecture",
        ["pdf.secciones_pe"] = "PE sections",
        ["pdf.col_nombre"] = "Name",
        ["pdf.col_caracteristicas"] = "Characteristics",
        ["pdf.imports_titulo"] = "Imports",
        ["pdf.imports_dlls"] = "DLLs",
        ["pdf.col_dll"] = "DLL",
        ["pdf.col_funciones"] = "Functions",
        ["pdf.iocs_titulo"] = "Indicators of compromise (IOCs)",
        ["pdf.iocs_urls"] = "URLs",
        ["pdf.iocs_ips"] = "IP addresses",
        ["pdf.iocs_dominios"] = "Domains",
        ["pdf.iocs_registro"] = "Registry keys",
        ["pdf.iocs_rutas"] = "File paths",
        ["pdf.yara_coincidencias"] = "YARA matches",
        ["pdf.yara_cadenas"] = "Strings",
        ["pdf.unidades_disco"] = "Disk drives",
        ["pdf.col_letra"] = "Letter",
        ["pdf.col_tipo"] = "Type",
        ["pdf.col_fs"] = "FS",
        ["pdf.col_total"] = "Total",
        ["pdf.col_libre"] = "Free",
        ["pdf.col_uso"] = "Use%",
        ["pdf.proteccion_titulo"] = "Protection software",
        ["pdf.col_producto"] = "Product",
        ["pdf.col_estado"] = "Status",
        ["pdf.startup_carpetas"] = "Startup applications (folders)",
        ["pdf.col_origen"] = "Source",
        ["pdf.col_comando"] = "Command",
        ["pdf.startup_registro"] = "Registry startup entries",
        ["pdf.col_clave"] = "Key",
        ["pdf.procesos_titulo"] = "Running processes",
        ["pdf.col_pid"] = "PID",
        ["pdf.col_memoria"] = "Memory",
        ["pdf.col_hilos"] = "Threads",
        ["pdf.col_ruta"] = "Path",
        ["pdf.hosts_titulo"] = "Hosts file",
        ["pdf.col_host"] = "Host",
        ["pdf.estado_sospechosa"] = "⚠ Suspicious",
        ["pdf.conexiones_titulo"] = "Network connections",
        ["pdf.col_proto"] = "Proto",
        ["pdf.col_local"] = "Local",
        ["pdf.col_remoto"] = "Remote",
        ["pdf.muestras_catalogo"] = "Catalog",
        ["pdf.muestras_total"] = "samples",
        ["pdf.col_familia"] = "Family",
        ["pdf.col_riesgo"] = "Risk",
        ["pdf.col_ingreso"] = "Added",
        ["pdf.sin_clasificar"] = "(unclassified)",
        ["pdf.netsniff_paquetes"] = "captured packets",
        ["pdf.netsniff_kpi_paquetes"] = "Packets",
        ["pdf.netsniff_kpi_bytes"] = "Bytes",
        ["pdf.netsniff_kpi_hosts"] = "Unique hosts",
        ["pdf.netsniff_kpi_duracion"] = "Duration",
        ["pdf.netsniff_distribucion"] = "Distribution by protocol",
        ["pdf.netsniff_paquetes_titulo"] = "Recent packets",
        ["pdf.col_hora"] = "Time",
        ["pdf.col_servicio"] = "Service",
        ["pdf.col_bytes_short"] = "Bytes",
        ["pdf.urlscan_url"] = "Analyzed URL",
        ["pdf.urlscan_resultado"] = "Analysis result",
        ["pdf.urlscan_consenso"] = "Engine consensus",
        ["pdf.urlscan_motores"] = "Antivirus engines",
        ["pdf.urlscan_categoria"] = "Category",
        ["pdf.urlscan_metadata"] = "Technical info",
        ["pdf.footer_generado"] = "Auto-generated report",
        ["pdf.pagina"] = "Page",
        ["pdf.pagina_de"] = "of",

        ["btn.cargar_archivo"] = "Load file",
        ["btn.exportar_reporte"] = "Export report",
        ["btn.exportar_pdf"] = "Export PDF",
        ["btn.guardar_cambios"] = "Save changes",
        ["btn.aplicar_filtros"] = "Apply filters",
        ["btn.aplicar_blacklist"] = "Apply blacklist",
        ["btn.probar_ejecucion"] = "Test execution",
        ["btn.volcar_memoria"] = "Dump memory",

        ["col.nombre"] = "Name",
        ["col.tipo"] = "Type",
        ["col.tamano"] = "Size",
        ["col.familia"] = "Family",
        ["col.riesgo"] = "Risk",
        ["col.estado"] = "Status",
        ["col.proceso"] = "Process",
        ["col.memoria"] = "Memory",
        ["col.direccion"] = "Address",
        ["col.operacion"] = "Operation",
        ["col.linea_comando"] = "Command line",
        ["col.accion"] = "Action",
        ["col.entropia"] = "Entropy",
        ["col.sospechosa"] = "Suspicious",
        ["col.caracteristicas"] = "Characteristics",
        ["col.tamano_virtual"] = "Virtual size",
        ["col.tamano_crudo"] = "Raw size",
        ["col.categoria"] = "Category",

        ["pag.estatico.subtitulo"] = "Deep PE inspection: strings, IOCs, packers and YARA rules",
        ["pag.estatico.no_pe"] = "No PE header available for this file.",
        ["pag.estatico.riesgo"] = "Risk: ",
        ["pag.estatico.tipo_magico"] = "Magic type",
        ["pag.estatico.tipo_maquina"] = "Machine type",
        ["pag.estatico.tipo_ejecutable"] = "Executable type",
        ["pag.estatico.num_secciones"] = "# Sections",
        ["pag.estatico.punto_entrada"] = "Entry point",
        ["pag.estatico.base_imagen"] = "Image base",
        ["pag.estatico.entropia_total"] = "Total entropy",

        ["pag.dinamico.subtitulo"] = "Local sandbox monitoring processes, files, registry and network",

        ["pag.intel.iocs_help"] = "You can paste multiple IOCs separated by comma or newline",
        ["pag.intel.puntuacion_global"] = "Global score",
        ["pag.intel.reputacion"] = "reputation",

        ["pag.muestras.guardar"] = "Save changes",
        ["pag.muestras.eliminar"] = "Delete",
        ["pag.muestras.exportar"] = "Export",
        ["pag.muestras.sin_seleccion"] = "No selection",
        ["pag.muestras.riesgo_critico"] = "80+ critical",

        ["pag.ml.caract_extraidas"] = "Extracted features",
        ["pag.ml.familia_predicha"] = "Predicted family",
        ["pag.ml.sin_datos"] = "No data. Pick a file and classify it.",
        ["pag.ml.sin_clasificacion"] = "No classification yet.",
        ["pag.ml.distribucion_probs"] = "Probability distribution",
        ["pag.ml.vecinos"] = "Nearest neighbors",

        ["pag.visual.modo.entropia"] = "Entropy map by section",
        ["pag.visual.modo.imports"] = "Imports distribution by DLL",
        ["pag.visual.modo.iocs"] = "Detected IOCs graph",
        ["pag.visual.modo.histograma"] = "Byte histogram",
        ["pag.visual.modo.strings"] = "Suspicious strings map",
        ["pag.visual.modo.layout"] = "PE sections layout",
        ["pag.visual.modo.arbol"] = "System process tree",

        ["pag.plugins.como_crear"] = "How to create a plugin?",
        ["pag.plugins.entrada_prueba"] = "test input",
        ["pag.plugins.salida_prueba"] = "Test output",
        ["pag.plugins.descripcion_etiqueta"] = "Description",
        ["pag.plugins.version_etiqueta"] = "Version",

        ["pag.pro.tab_dump"] = "Memory dump",
        ["pag.pro.tab_deobfusc"] = "Deobfuscation",
        ["pag.pro.tab_extract"] = "Config extraction",
        ["pag.pro.tab_emulation"] = "Emulation",
        ["pag.pro.bytes_help"] = "Paste hex bytes (separated by space or contiguous):",
        ["pag.pro.tecnica"] = "Technique",
        ["pag.pro.puntuacion"] = "Score",

        ["pag.sistema.menu.copiar_nombre"] = "Copy name",
        ["pag.sistema.menu.copiar_remoto"] = "Copy remote address",
        ["pag.sistema.menu.copiar_local"] = "Copy local address",
        ["pag.sistema.menu.bloquear_ip"] = "Block IP in firewall (Windows)",
        ["pag.sistema.menu.abrir_ubicacion_ejec"] = "Open executable location",
        ["pag.sistema.menu.abrir_ubicacion"] = "Open location",

        ["pag.netsniff.lista_negra"] = "IP blacklist",
        ["pag.netsniff.lista_negra_help"] = "One IP per line. Packets to/from these IPs are highlighted as alerts.",
        ["pag.netsniff.por_protocolo"] = "By protocol",
        ["pag.netsniff.trafico_60"] = "Traffic (last 60s)",
        ["pag.netsniff.ocultar_local"] = "Hide local traffic",
        ["pag.netsniff.sin_alertas"] = "No alerts yet",
        ["pag.netsniff.kpi.trafico"] = "Traffic",
        ["pag.netsniff.kpi.duracion"] = "Duration",
        ["pag.netsniff.kpi.hosts"] = "Unique hosts",

        ["pag.urlscan.tab_motores"] = "Engines",
        ["pag.urlscan.tab_heuristicas"] = "Heuristics",
        ["pag.urlscan.tab_info"] = "Info",
        ["pag.urlscan.tab_fuentes"] = "Sources / errors",
        ["pag.urlscan.kpi.maliciosos"] = "Malicious",
        ["pag.urlscan.kpi.sospechosos"] = "Suspicious",
        ["pag.urlscan.kpi.limpios"] = "Clean",
        ["pag.urlscan.kpi.sin_deteccion"] = "Undetected",
        ["pag.urlscan.servicios_consultados"] = "Services consulted",
        ["pag.urlscan.avisos_errores"] = "Warnings / errors",

        ["pag.inicio.importar_muestra"] = "Import sample",
        ["pag.inicio.sin_muestras"] = "No samples catalogued yet. Import files to start.",

        ["acerca_de.tecnologias"] = "Technologies",
        ["acerca_de.version"] = "Version 1.0.0",

        ["msg.cargando_plugins"] = "Loading plugins...",
        ["msg.cargando_config"] = "Loading configuration...",
        ["msg.inicializando_bd"] = "Initializing database...",
        ["msg.conectando_intel"] = "Connecting intelligence services...",
        ["msg.idioma_cambiado"] = "Language changed to English",
        ["msg.config_guardada"] = "Settings saved",
        ["msg.config_restablecida"] = "Settings reset",
        ["msg.confirmar_reset"] = "Reset all values to defaults?",
        ["msg.error_admin"] = "Operation failed. You probably need to run Malyzer as administrator.",
        ["msg.requiere_admin"] = "Are you running as administrator?",
        ["msg.confirmar_accion"] = "Confirm action",
        ["msg.confirmar_eliminar"] = "Confirm deletion",
        ["msg.adv_seguridad"] = "Security warning",
        ["msg.continuar"] = "Continue?",
        ["msg.error"] = "Error",
        ["msg.exito"] = "Success",
        ["msg.archivo_no_encontrado"] = "File not found on disk.",
        ["msg.sin_seleccion"] = "Nothing selected",
        ["msg.no_muestras"] = "There are no samples in the repository.",
        ["msg.no_muestras_repo"] = "No samples in repository. Import some first from the Samples page.",
        ["msg.no_muestras_export"] = "No samples to export.",
        ["msg.ingresar_url"] = "Enter a URL to analyze.",
        ["msg.no_browser"] = "Could not open browser",
        ["msg.pdf_exportado"] = "PDF exported",
        ["msg.pdf_abrir"] = "PDF exported. Open it now?",
        ["msg.pdf_correcto_abrir"] = "PDF exported successfully. Open it now?",
        ["msg.estatico_progreso"] = "Static analysis in progress",
        ["msg.estatico_completo"] = "Static analysis completed",
        ["msg.estatico_archivo_listo"] = "File loaded, ready to analyze",
        ["msg.estatico_error"] = "Analysis error",
        ["msg.dinamico_finalizado"] = "Dynamic analysis finished",
        ["msg.dinamico_error"] = "Dynamic analysis error",
        ["msg.url_analizando"] = "Analyzing URL across multiple services...",
        ["msg.url_completo"] = "Analysis complete",
        ["msg.url_no_heur"] = "No suspicious local heuristics detected.",
        ["msg.url_categoria_prefix"] = "Category: ",
        ["msg.captura_inicia"] = "Start a capture first.",
        ["msg.captura_seleccionar"] = "Select an adapter.",
        ["msg.captura_curso"] = "Capture in progress",
        ["msg.no_proc_dueno"] = "Could not resolve owner PID.",
        ["msg.no_proc_conexion"] = "Could not resolve owner process for the connection.\n\nTry \"Kill owner process\" or run Malyzer as administrator.",
        ["msg.no_firewall"] = "Could not add the rule. Are you running as administrator?",
        ["msg.firewall_aplicada"] = "Firewall rule added for",
        ["msg.proc_terminado"] = "terminated",
        ["msg.proc_suspendido"] = "suspended",
        ["msg.proc_reanudado"] = "resumed",
        ["msg.host_comentado"] = "Line commented in hosts",
        ["msg.host_eliminado"] = "Line removed from hosts",
        ["msg.reg_eliminado"] = "Registry entry deleted",
        ["msg.entrada_eliminada"] = "Entry deleted",
        ["msg.inspeccion_progreso"] = "Inspecting system...",
        ["msg.inspeccion_completa"] = "Inspection complete",
        ["msg.inspeccion_error"] = "Error inspecting system",
        ["msg.dump_progreso"] = "Dumping memory...",
        ["msg.dump_titulo"] = "Save memory dump",
        ["msg.confirmar_matar"] = "Kill process",
        ["msg.confirmar_matar_dueno"] = "Kill owner process for",
        ["msg.confirmar_eliminar_archivo"] = "Delete the startup file?",
        ["msg.confirmar_eliminar_reg"] = "Delete the registry entry?",
        ["msg.confirmar_comentar_linea"] = "Comment line",
        ["msg.confirmar_eliminar_linea"] = "Delete line",
        ["msg.confirmar_bloquear"] = "Create firewall rule to block all outbound connections to",
        ["msg.confirmar_bloquear_admin"] = "Requires administrator privileges.",
        ["msg.confirmar_cerrar_conex"] = "To close the connection the owner process must be terminated",
        ["msg.confirmar_eliminar_muestra"] = "Delete sample",
        ["msg.importadas"] = "Imported",
        ["msg.muestras_count"] = "sample(s)",
        ["msg.muestras_errores"] = "errors",
        ["msg.error_cargando_muestras"] = "Error loading samples",
        ["msg.exportado_a"] = "Exported to",
        ["msg.adv_dinamico"] = "You're about to execute the sample. Make sure you're in an isolated environment (VM/sandbox).",
        ["msg.import_titulo"] = "Import samples",
        ["msg.import_titulo_uno"] = "Import sample",
        ["msg.export_titulo_muestra"] = "Export sample",
        ["msg.export_titulo_muestras_pdf"] = "Export samples to PDF",
        ["msg.export_titulo_pcap"] = "Export capture to PCAP",
        ["msg.export_titulo_estatico"] = "Export report to PDF",
        ["msg.export_titulo_sistema"] = "Export system report",
        ["msg.export_titulo_netsniff"] = "Export Netsniff report",
        ["msg.export_titulo_url"] = "Export URL analysis to PDF",
        ["msg.export_titulo_estatico_txt"] = "Export report",
        ["msg.filtro_pdf"] = "PDF (*.pdf)|*.pdf",
        ["msg.filtro_pcap"] = "PCAP capture (*.pcap)|*.pcap",
        ["msg.filtro_dump"] = "Mini-dump (*.dmp)|*.dmp",
        ["msg.filtro_todos"] = "All files (*.*)|*.*",
        ["msg.filtro_ejecutables"] = "Executable and other files (*.*)|*.*",
        ["msg.filtro_yara"] = "Folder with YARA rules (.yar)",
        ["msg.kpi_total"] = "Database",
        ["msg.kpi_critico"] = "CRITICAL",
        ["msg.kpi_minimo"] = "MINIMUM",
        ["msg.proc_pid"] = "Process PID",
        ["msg.conexion_cerrada"] = "connection closed",
        ["msg.viz_lista"] = "Visualization ready",
        ["msg.viz_no_pe"] = "File has no PE sections (not a PE?)",
        ["msg.viz_sin_secciones"] = "No sections (not a valid PE)",
        ["msg.viz_sin_imports"] = "File has no imports.",
        ["msg.viz_sin_iocs"] = "No IOCs detected in the file.",
        ["msg.viz_sin_strings"] = "No strings with known keywords found.",
        ["msg.viz_no_proc"] = "Could not enumerate system processes.",
        ["msg.viz_analizando"] = "Analyzing for visualization...",
        ["msg.viz_seleccionar_muestra"] = "Select sample from repository",
        ["msg.url_validar"] = "Services consulted",
        ["msg.url_sin_meta"] = "No metadata available.",
        ["msg.url_sin_fuentes"] = "(none)",
        ["msg.url_sin_errores"] = "(no errors)",
        ["msg.cls_completo"] = "Classification completed",
        ["msg.cls_grupos_completo"] = "Grouping completed",
        ["msg.cls_agrupando"] = "Grouping samples from repository...",
        ["msg.url_sin_externas"] = "No external sources (configure API keys in Settings)",
        ["msg.url_fuentes_prefix"] = "Sources: ",

        ["veredicto.alto"] = "High risk · Probably malicious",
        ["veredicto.medio"] = "Medium risk · Suspicious",
        ["veredicto.bajo"] = "Low risk · Anomalies detected",
        ["veredicto.limpio"] = "Clean · No clear indicators",
        ["tipo.pe"] = "PE / Windows executable",
        ["tipo.elf"] = "ELF / Linux executable",
        ["tipo.macho64"] = "Mach-O 64-bit",
        ["tipo.macho32"] = "Mach-O 32-bit",
        ["tipo.zip"] = "ZIP / OOXML / JAR archive",
        ["tipo.rar"] = "RAR archive",
        ["tipo.7z"] = "7-Zip archive",
        ["tipo.pdf"] = "PDF document",
        ["tipo.ole"] = "OLE / Legacy Office document",
        ["tipo.script"] = "Script (shebang)",
        ["tipo.cab"] = "Microsoft Cabinet",
        ["tipo.binario"] = "binary data",
        ["tipo.desconocido"] = "unknown",

        ["yara.upx.titulo"] = "UPX packer marker",
        ["yara.antivm.titulo"] = "Anti-VM and anti-debug techniques",
        ["yara.injection.titulo"] = "Process injection APIs",
        ["yara.powershell.titulo"] = "Encoded PowerShell execution",
        ["yara.browsers.titulo"] = "Browser profile and data access",
        ["yara.persistence.titulo"] = "Registry keys used for persistence",
        ["yara.keylogger.titulo"] = "Keylogger-typical APIs",
        ["yara.mimikatz.titulo"] = "Mimikatz-typical strings",
        ["yara.ransomware.titulo"] = "Generic ransomware indicators",
        ["yara.antianalysis.titulo"] = "Suspicious · anti-analysis techniques",

        ["pag.adv.titulo"] = "Advanced intelligence",
        ["pag.adv.subtitulo"] = "Sample diff, MITRE ATT&CK mapping, Capstone-based decoding, dynamic ETW and LLM triage",
        ["pag.adv.tab_diff"] = "Sample diff",
        ["pag.adv.tab_mitre"] = "MITRE ATT&CK",
        ["pag.adv.tab_decoder"] = "Decoder (Capstone)",
        ["pag.adv.tab_etw"] = "Dynamic ETW",
        ["pag.adv.tab_multi"] = "Multi-format",
        ["pag.adv.multi_help"] = "Deep multi-format analysis. Auto-detects file type (PE, APK, Office, PDF, scripts, JAR) and applies specific analysis to each: dangerous permissions, VBA macros, JavaScript in PDFs, dynamic execution in scripts, etc.",
        ["pag.adv.multi_analizar"] = "Analyze file",
        ["pag.adv.diff_help"] = "Compare two samples: SSDeep, common imports, sections, YARA rules and IOCs. Useful to detect variants of the same family.",
        ["pag.adv.diff_comparar"] = "Compare A vs B",
        ["pag.adv.diff_buscar_similares"] = "Find similar in repo",
        ["pag.adv.diff_indexar"] = "Index SSDeep in repo",
        ["pag.adv.mitre_help"] = "Automatic MITRE ATT&CK technique mapping based on imports, YARA, IOCs and behavior.",
        ["pag.adv.mitre_mapear"] = "Map",
        ["pag.adv.decoder_help"] = "Capstone disassembly to detect stack strings, XOR loops, API hashing and other obfuscation techniques.",
        ["pag.adv.decoder_decodificar"] = "Decode",
        ["pag.adv.etw_help"] = "Real-time tracing via Event Tracing for Windows. Capture file/registry/network/process events of a process and its children. Requires admin.",
        ["pag.adv.etw_total"] = "Events",
        ["pag.adv.etw_archivos"] = "Files",
        ["pag.adv.etw_registro"] = "Registry",
        ["pag.adv.etw_red"] = "Network",
        ["pag.adv.etw_procesos"] = "Processes",


        ["pag.netsniff.menu_geoip"] = "🌍 Inspect IP (GeoIP / WHOIS)",
        ["pag.netsniff.menu_copiar_ip"] = "Copy remote IP",
        ["pag.netsniff.menu_virustotal"] = "Search on VirusTotal",
        ["pag.netsniff.menu_abuseipdb"] = "Search on AbuseIPDB",
        ["pag.netsniff.menu_shodan"] = "Search on Shodan",

        ["btn.detener"] = "Stop",
        ["btn.listar_procesos"] = "List processes",
        ["btn.agrupar_repo"] = "Group repository",
        ["btn.clasificar"] = "Classify",
        ["btn.seleccionar"] = "Select",
        ["btn.abrir_directorio"] = "Open directory",
        ["btn.abrir_archivo_hosts"] = "Open hosts file",
        ["btn.copiar_ruta"] = "Copy path",

        ["lbl.archivo"] = "File:",
        ["lbl.archivo_simple"] = "File",
        ["lbl.ruta"] = "Path",
        ["lbl.comando_ruta"] = "Command / Path",
        ["lbl.esperando_archivo"] = "Waiting for file",
        ["lbl.sin_archivo"] = "(no file loaded)",
        ["lbl.auto_detectar"] = "auto-detect",
        ["lbl.muestras_count_lower"] = "samples",

        ["pag.pro.advertencia_volcado"] = "This function produces a FULL memory dump. Only use in a virtual machine with admin privileges. Dumps can be very large (GB).",
        ["pag.ml.modelo_entrenado"] = "Model trained with {0} examples",
        ["pag.ml.agrupamiento_grupos"] = "Similarity grouping: {0} groups",
        ["pag.acerca.advertencia_titulo"] = "⚠ WARNING",
        ["pag.acerca.advertencia_texto"] = "This tool executes and analyzes malware samples. Always use isolated virtual machines with snapshots and restricted networking. Never run samples on production systems.",

        // ───── v1.1 ─────
        ["pag.intel.tab_lookup"] = "IOC lookup",
        ["pag.intel.tab_upload"] = "Upload sample",
        ["pag.intel.usar_mb"] = "Also query MalwareBazaar",
        ["pag.intel.usar_tf"] = "Also query ThreatFox",
        ["pag.intel.upload_titulo"] = "Upload sample to analysis service",
        ["pag.intel.upload_aviso"] = "Uploading a sample to VirusTotal or MalwareBazaar makes it public to the threat intel community. Only upload samples you intend to share.",
        ["pag.intel.upload_archivo"] = "File to upload",
        ["pag.intel.upload_destino"] = "Destinations",
        ["pag.intel.upload_vt"] = "VirusTotal (requires API key)",
        ["pag.intel.upload_mb"] = "MalwareBazaar (requires abuse.ch key)",
        ["pag.intel.upload_meta"] = "Optional metadata (MalwareBazaar)",
        ["pag.intel.upload_etiquetas"] = "Tags",
        ["pag.intel.upload_comentario"] = "Comment",
        ["pag.intel.upload_publico"] = "Public upload (visible to community)",
        ["btn.subir"] = "Upload sample",
        ["btn.exportar_pdf"] = "Export PDF",
        ["estado.subiendo"] = "Uploading sample...",
        ["estado.subida_completada"] = "Upload completed",
        ["estado.subida_cancelada"] = "Upload cancelled",
        ["msg.confirmar_subida"] = "You are about to upload this sample to a public analysis service. It will be accessible by the community. Continue?",
        ["msg.elegir_muestra"] = "Choose sample",
        ["msg.elegir_muestra_primero"] = "First choose a file to upload",
        ["msg.elegir_destino_subida"] = "You must choose at least one destination",
        ["msg.vt_sin_clave"] = "VirusTotal: API key not configured (Configuration → API keys)",
        ["msg.mb_sin_clave"] = "MalwareBazaar: abuse.ch key not configured",
        ["msg.sin_resultados"] = "No results to export",
        ["msg.sin_subidas"] = "No uploads to export",
        ["msg.guardar_pdf_intel"] = "Save Threat Intel report",
        ["msg.guardar_pdf_subidas"] = "Save Uploads report",
        ["pag.estatico.tab_firma"] = "Digital signature",
        ["pag.estatico.firma_titulo"] = "Authenticode verification",
        ["pag.estatico.firma_estado"] = "Status",
        ["pag.estatico.firma_sujeto"] = "Subject",
        ["pag.estatico.firma_emisor"] = "Issuer",
        ["pag.estatico.firma_emision"] = "Issued",
        ["pag.estatico.firma_vencimiento"] = "Expiration",
        ["pag.estatico.firma_algoritmo"] = "Algorithm",
        ["pag.estatico.firma_huella"] = "Thumbprint (SHA-1)",
        ["pag.estatico.firma_serie"] = "Serial number",
        ["pag.estatico.firma_chequeo"] = "Checks",
        ["pag.estatico.rich_titulo"] = "Rich Header (compiler metadata)",
        ["pag.estatico.rich_presente"] = "Present",
        ["pag.estatico.rich_compilador"] = "Estimated compiler",
        ["pag.estatico.rich_producto"] = "Product",
        ["pdf.title.intel"] = "Threat Intel report",
        ["pdf.title.subidas"] = "Uploads report",
        ["pdf.title.multiformato"] = "Multi-format analysis",
        ["pdf.intel_total"] = "indicators",
        ["pdf.intel_kpi_total"] = "Indicators",
        ["pdf.intel_kpi_global"] = "Global score",
        ["pdf.intel_kpi_alta"] = "High reputation",
        ["pdf.intel_kpi_media"] = "Medium reputation",
        ["pdf.intel_resumen"] = "Weighted global score",
        ["pdf.intel_por_fuente"] = "Distribution by source",
        ["pdf.intel_indicadores"] = "Queried indicators",
        ["pdf.col_fuente"] = "Source",
        ["pdf.col_valor"] = "Value",
        ["pdf.col_reputacion"] = "Reputation",
        ["pdf.col_detalles"] = "Details",
        ["pdf.col_descripcion"] = "Description",
        ["pdf.col_severidad"] = "Severity",
        ["pdf.col_tamano"] = "Size",
        ["pdf.subidas_total"] = "uploads",
        ["pdf.subidas_kpi_total"] = "Total",
        ["pdf.subidas_kpi_exitosas"] = "Successful",
        ["pdf.subidas_kpi_existentes"] = "Already existing",
        ["pdf.subidas_kpi_errores"] = "With errors",
        ["pdf.subidas_detecciones"] = "Detections",
        ["pdf.multi_kpi_indicadores"] = "Indicators",
        ["pdf.metadata"] = "Metadata",
        ["pdf.indicadores"] = "Detected indicators",
        ["pdf.strings_relevantes"] = "Relevant strings",
        ["pdf.veredicto"] = "Verdict",
    };
}
